const DEVELOPMENT = 'DEV';
const PRODUCTION = 'PRD';
const DEFAULT_PAGE_LIMIT = 10;
const PAGINATION_ERROR = 'PAGINATION_ERROR';

export default {
  DEVELOPMENT,
  PRODUCTION,
  DEFAULT_PAGE_LIMIT,
  PAGINATION_ERROR,
};
